language: ruby
rvm:
- 2.4.0
install: bundle install
script: bundle exec rspec
notifications:
  slack:
    rooms:
      - 8thlight: ozNrx4SLg6rL4bkomaWojNYn#tom-apprenticeship
    on_success: always
    on_failure: never
    template:
      - "%{repository_name} #%{build_number} (%{commit}): %{commit_subject}"
      - "%{branch} - %{compare_url}"
